language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - TWINE_USERNAME=SethMMorton
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  # First clone the specific release tag, then move interesting contents into CWD.
  - git clone --branch 2.0.3 --single-branch --depth 1 https://github.com/SethMMorton/fastnumbers.git repo
  - mv repo/setup.* repo/include repo/src .
  # Install and execute the builder.
  - $PIP install cibuildwheel==0.8.0 twine
  - cibuildwheel --output-dir wheelhouse
  # Release the built wheels.
  - twine upload wheelhouse/*.whl
