environment:
  CIBW_SKIP: cp33-*
  TWINE_USERNAME: SethMMorton
  # Note: TWINE_PASSWORD is set in Appveyor settings

build_script:
  # First clone the specific release tag, then move interesting contents into CWD.
  - git clone --branch 2.0.4 --single-branch --depth 1 https://github.com/SethMMorton/fastnumbers.git repo
  - move repo\include .
  - move repo\src .
  - move repo\setup.py .
  # Install and execute the builder.
  - pip install cibuildwheel==0.8.0
  - cibuildwheel --output-dir wheelhouse
  # Release the built wheels.
  - pip install twine
  - twine upload wheelhouse/*.whl

